In [1]:
import sklearn
import pandas as pd
import random

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'

In [3]:
ionos = pd.read_csv(url, header=None)

In [5]:
the_order = [n for n in range(0,351)]
the_big_order = []

for i in range(0,1000):
    random.seed(i)
    random.shuffle(the_order)
    the_big_order.append(the_order)

In [6]:
the_order = the_big_order[0]

In [7]:
feature_columns = [x+1 for x in range(0,33)]
target_columns = 34
ionos[feature_columns].head()

,1,2,3,4,5,6,7,8,9,10,...,24,25,26,27,28,29,30,31,32,33
0,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,0.85243,...,0.56811,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300
1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,0.50874,...,-0.20332,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447
2,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,0.73082,...,0.57528,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238
3,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,0.00000,...,1.00000,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000
4,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,0.52798,...,0.03286,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697

>>> from sklearn.datasets import load_iris
>>> from sklearn.linear_model import LogisticRegression
>>> X, y = load_iris(return_X_y=True)
>>> clf = LogisticRegression(random_state=0, solver='lbfgs',
...                          multi_class='multinomial').fit(X, y)
>>> clf.predict(X[:2, :])
array([0, 0])
>>> clf.predict_proba(X[:2, :]) 
array([[9.8...e-01, 1.8...e-02, 1.4...e-08],
       [9.7...e-01, 2.8...e-02, ...e-08]])
>>> clf.score(X, y)
0.97...

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
the_order[0:10]

In [ ]:
a = [1,2,3,4,5,6]

In [ ]:
a[0:2], a[2:4]

In [126]:
count = 0
for i in range(, len(the_order)+1-70):
    count += 1
    row_train = the_order[0:i]
    len_row_test = (len(row_train) // 4)
    if len_row_test == 0:
        len_row_test += 1
    row_test = the_order[i:i+len_row_test]
    lr = LogisticRegression(random_state=0, solver='lbfgs')
    nb = GaussianNB()
    knn = KNeighborsClassifier(n_neighbors=5)    

    lr.fit(ionos.iloc[row_train, feature_columns], ionos.iloc[row_train, target_columns])
    nb.fit(ionos.iloc[row_train, feature_columns], ionos.iloc[row_train, target_columns])
    knn.fit(ionos.iloc[row_train, feature_columns], ionos.iloc[row_train, target_columns])
    lr_prediction = lr.predict(ionos.iloc[row_test, feature_columns])
    nb_prediction = nb.predict(ionos.iloc[row_test, feature_columns])
    knn_prediction = knn.predict(ionos.iloc[row_test, feature_columns])

    print(lr_prediction)
    print(nb_prediction)
    print(knn_prediction)
    print(ionos.iloc[row_test, target_columns])
    if count == 10:
        break

['g']
['g']
['g']
241    g
Name: 34, dtype: object
['g']
['g']
['g']
209    g
Name: 34, dtype: object
['g']
['g']
['g']
196    b
Name: 34, dtype: object
['b' 'g']
['b' 'b']
['g' 'g']
338    g
170    b
Name: 34, dtype: object
['g' 'g']
['b' 'g']
['g' 'g']
170    b
211    g
Name: 34, dtype: object
['g' 'g']
['g' 'g']
['g' 'g']
211    g
321    g
Name: 34, dtype: object
['g' 'g']
['g' 'g']
['g' 'g']
321    g
139    g
Name: 34, dtype: object
['g' 'g' 'g']
['g' 'b' 'g']
['g' 'g' 'g']
139    g
135    g
348    g
Name: 34, dtype: object
['g' 'g' 'g']
['b' 'g' 'b']
['g' 'g' 'g']
135    g
348    g
194    b
Name: 34, dtype: object
['g' 'g' 'g']
['g' 'b' 'g']
['g' 'g' 'g']
348    g
194    b
313    g
Name: 34, dtype: object